#ifndef PS5TORRENT_WEB_CONTENT_H
#define PS5TORRENT_WEB_CONTENT_H

/* Generated from src/web/index.html by scripts/embed_web.py. */
static const char web_index_html[] =
"<!doctype html>\n"
"<html lang=\"pt-BR\">\n"
"<head>\n"
"  <meta charset=\"utf-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1,viewport-fit=cover\">\n"
"  <meta name=\"theme-color\" content=\"#07101f\">\n"
"  <title>PS5Torrent</title>\n"
"  <style>\n"
"    *{box-sizing:border-box}\n"
"    :root{--bg:#050a13;--panel:#0c1524;--panel2:#111d30;--line:#23344c;--text:#f4f8ff;--muted:#93a4ba;--blue:#4fa7ff;--blue2:#1769e0;--cyan:#54e2db;--green:#45d483;--yellow:#ffbe55;--red:#ff6b71;--shadow:0 22px 60px rgba(0,0,0,.34)}\n"
"    html{background:var(--bg)}\n"
"    body{margin:0;min-height:100vh;color:var(--text);font:15px/1.45 -apple-system,BlinkMacSystemFont,\"Segoe UI\",Arial,sans-serif;background:radial-gradient(circle at 82% -8%,rgba(34,118,255,.18),transparent 35%),radial-gradient(circle at -5% 86%,rgba(33,226,217,.08),transparent 28%),var(--bg)}\n"
"    button,input,textarea{font:inherit}\n"
"    button{color:inherit}\n"
"    button:focus-visible,input:focus-visible,textarea:focus-visible,.path:focus-visible{outline:3px solid #fff;outline-offset:3px;box-shadow:0 0 0 7px rgba(79,167,255,.38)}\n"
"    .shell{max-width:1500px;margin:auto;padding:30px clamp(22px,4vw,68px) 64px}\n"
"    .topbar{display:flex;align-items:center;gap:18px;margin-bottom:28px}\n"
"    .brand{display:flex;align-items:center;gap:14px;min-width:0}\n"
"    .logo{position:relative;display:grid;place-items:center;width:54px;height:54px;flex:0 0 auto;border-radius:17px;background:linear-gradient(145deg,#1e75ee,#58d8ea);box-shadow:0 12px 32px rgba(30,117,238,.34)}\n"
"    .logo svg{width:32px;height:32px;filter:drop-shadow(0 4px 8px rgba(0,0,0,.25))}\n"
"    .brand h1{margin:0;font-size:22px;letter-spacing:-.4px}\n"
"    .brand p{margin:2px 0 0;color:var(--muted);font-size:12px}\n"
"    .connection{margin-left:auto;display:flex;align-items:center;gap:9px;padding:9px 13px;border:1px solid var(--line);border-radius:999px;background:rgba(12,21,36,.84);font-size:12px;color:var(--muted)}\n"
"    .connection-dot{width:9px;height:9px;border-radius:50%;background:var(--yellow);box-shadow:0 0 0 4px rgba(255,190,85,.12)}\n"
"    .connection.online .connection-dot{background:var(--green);box-shadow:0 0 0 4px rgba(69,212,131,.12)}\n"
"    .connection.offline .connection-dot{background:var(--red);box-shadow:0 0 0 4px rgba(255,107,113,.12)}\n"
"    .connection.online .connection-label{color:#d9ffea}\n"
"    .toolbar{display:flex;gap:10px}\n"
"    .btn{border:1px solid var(--line);border-radius:12px;min-height:44px;padding:0 17px;display:inline-flex;align-items:center;justify-content:center;gap:9px;background:var(--panel2);cursor:pointer;font-weight:700;transition:transform .16s,border-color .16s,background .16s}\n"
"    .btn:hover{border-color:#54739b;transform:translateY(-1px)}\n"
"    .btn.primary{border-color:transparent;background:linear-gradient(135deg,var(--blue2),#268cf7);box-shadow:0 10px 25px rgba(23,105,224,.25)}\n"
"    .btn.danger{border-color:rgba(255,107,113,.35);background:rgba(255,107,113,.10);color:#ffc6c9}\n"
"    .btn.small{min-height:36px;padding:0 13px;font-size:12px;border-radius:9px}\n"
"    .btn:disabled{opacity:.5;cursor:not-allowed;transform:none}\n"
"    .icon{width:18px;height:18px;display:inline-block}\n"
"    .hero{position:relative;overflow:hidden;padding:30px;border:1px solid #1e3b61;border-radius:24px;background:linear-gradient(125deg,rgba(17,42,75,.95),rgba(8,19,34,.96) 62%,rgba(11,35,48,.96));box-shadow:var(--shadow);margin-bottom:18px}\n"
"    .hero:after{content:\"\";position:absolute;width:330px;height:330px;right:-105px;top:-190px;border:50px solid rgba(79,167,255,.08);border-radius:50%}\n"
"    .hero-row{display:flex;align-items:flex-end;justify-content:space-between;gap:26px;position:relative;z-index:1}\n"
"    .eyebrow{font-size:11px;font-weight:800;letter-spacing:1.6px;text-transform:uppercase;color:var(--cyan)}\n"
"    .hero h2{font-size:clamp(27px,3.2vw,45px);line-height:1.08;letter-spacing:-1.6px;margin:8px 0 10px;max-width:730px}\n"
"    .hero-copy{margin:0;color:#acbdd0;max-width:690px}\n"
"    .hero-meta{display:flex;gap:8px;margin-top:20px;flex-wrap:wrap}\n"
"    .chip{font-size:11px;font-weight:700;color:#bcd0e7;border:1px solid rgba(129,166,207,.23);background:rgba(4,11,20,.3);border-radius:999px;padding:6px 10px}\n"
"    .summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:18px 0}\n"
"    .metric{padding:18px;border:1px solid var(--line);border-radius:17px;background:linear-gradient(145deg,rgba(17,29,48,.92),rgba(9,17,30,.92));min-width:0}\n"
"    .metric-label{display:flex;align-items:center;gap:8px;color:var(--muted);font-size:12px;margin-bottom:7px}\n"
"    .metric-value{font-size:clamp(20px,2.3vw,31px);font-weight:800;letter-spacing:-.7px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}\n"
"    .metric-sub{font-size:11px;color:#60758f;margin-top:3px}\n"
"    .panel{border:1px solid var(--line);border-radius:20px;background:rgba(10,18,31,.93);box-shadow:0 16px 45px rgba(0,0,0,.18);overflow:hidden}\n"
"    .panel-head{display:flex;align-items:center;gap:16px;padding:20px 22px;border-bottom:1px solid var(--line)}\n"
"    .panel-title{font-size:18px;font-weight:800;letter-spacing:-.3px}\n"
"    .panel-note{font-size:11px;color:var(--muted);margin-top:2px}\n"
"    .filters{margin-left:auto;display:flex;gap:5px;padding:4px;border:1px solid var(--line);background:#091220;border-radius:11px}\n"
"    .filter{border:0;background:transparent;color:var(--muted);padding:7px 11px;border-radius:8px;cursor:pointer;font-size:11px;font-weight:700}\n"
"    .filter.active{background:#1b304d;color:#fff}\n"
"    .torrent-list{padding:14px}\n"
"    .torrent{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:15px;padding:18px;border:1px solid #1d2d43;border-radius:15px;background:linear-gradient(140deg,#101c2e,#0b1422);margin-bottom:10px}\n"
"    .torrent:last-child{margin-bottom:0}\n"
"    .torrent:hover{border-color:#385a83}\n"
"    .torrent-top{display:flex;align-items:flex-start;gap:12px}\n"
"    .torrent-symbol{display:grid;place-items:center;width:40px;height:40px;flex:0 0 auto;border-radius:12px;background:rgba(79,167,255,.12);color:var(--blue)}\n"
"    .torrent-symbol svg{width:22px;height:22px}\n"
"    .torrent-name{font-size:15px;font-weight:800;line-height:1.3;word-break:break-word}\n"
"    .torrent-hash{font:10px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;color:#60758f;margin-top:4px;word-break:break-all}\n"
"    .state{display:inline-flex;align-items:center;gap:6px;margin-left:auto;padding:5px 9px;border-radius:999px;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.5px;white-space:nowrap;background:rgba(147,164,186,.10);color:#b8c5d4}\n"
"    .state:before{content:\"\";width:6px;height:6px;border-radius:50%;background:currentColor}\n"
"    .state-downloading{color:#78bbff;background:rgba(79,167,255,.12)}\n"
"    .state-done{color:#6ce39b;background:rgba(69,212,131,.11)}\n"
"    .state-seeding{color:#63e9df;background:rgba(84,226,219,.11)}\n"
"    .state-error{color:#ff8e93;background:rgba(255,107,113,.11)}\n"
"    .progress-line{display:flex;align-items:center;gap:12px;margin:15px 0 12px}\n"
"    .track{height:9px;flex:1;overflow:hidden;border-radius:99px;background:#050b13;border:1px solid #17263a}\n"
"    .fill{height:100%;min-width:0;border-radius:99px;background:linear-gradient(90deg,#2078e8,#59dbea);box-shadow:0 0 17px rgba(79,167,255,.35);transition:width .55s ease}\n"
"    .torrent.done .fill{background:linear-gradient(90deg,#28b86d,#63e0a0)}\n"
"    .pct{width:47px;text-align:right;font-size:13px;font-weight:800;color:#dcecff}\n"
"    .details{display:grid;grid-template-columns:repeat(5,minmax(78px,1fr));gap:8px}\n"
"    .detail{border-left:1px solid #22354e;padding-left:10px;min-width:0}\n"
"    .detail:first-child{border-left:0;padding-left:0}\n"
"    .detail span{display:block;color:#6f839d;font-size:10px;text-transform:uppercase;letter-spacing:.5px}\n"
"    .detail strong{display:block;font-size:12px;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}\n"
"    .save-path{font:10px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;color:#6e829c;margin-top:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}\n"
"    .torrent-actions{display:flex;align-items:center;gap:7px}\n"
"    .error-msg{grid-column:1/-1;padding:9px 11px;border-radius:9px;color:#ffc3c6;background:rgba(255,107,113,.08);font-size:11px}\n"
"    .empty{display:grid;place-items:center;text-align:center;min-height:290px;padding:35px;color:var(--muted)}\n"
"    .empty-mark{display:grid;place-items:center;width:66px;height:66px;border-radius:20px;background:#101e32;color:var(--blue);margin:0 auto 15px}\n"
"    .empty-mark svg{width:34px;height:34px}\n"
"    .empty strong{display:block;color:var(--text);font-size:17px;margin-bottom:5px}\n"
"    .hidden{display:none!important}\n"
"    .modal-backdrop{position:fixed;inset:0;z-index:100;background:rgba(0,5,12,.78);backdrop-filter:blur(12px);display:grid;place-items:center;padding:25px}\n"
"    .modal{width:min(720px,100%);max-height:92vh;overflow:auto;border:1px solid #35577e;border-radius:22px;background:#0b1626;box-shadow:0 30px 100px rgba(0,0,0,.62)}\n"
"    .modal-head{position:sticky;top:0;z-index:2;display:flex;align-items:center;padding:20px 22px;border-bottom:1px solid var(--line);background:rgba(11,22,38,.97)}\n"
"    .modal-head h3{margin:0;font-size:19px}\n"
"    .close{margin-left:auto;width:38px;height:38px;border:1px solid var(--line);border-radius:10px;background:#111f33;cursor:pointer;font-size:20px}\n"
"    .form{padding:22px}\n"
"    .label{display:block;color:#aabbd0;font-size:12px;font-weight:700;margin:0 0 7px}\n"
"    .drop{display:grid;place-items:center;text-align:center;min-height:125px;border:2px dashed #345579;border-radius:14px;background:#0c1a2c;color:#9fb1c7;cursor:pointer;padding:20px;transition:border .16s,background .16s}\n"
"    .drop:hover,.drop.has-file{border-color:var(--blue);background:rgba(79,167,255,.07)}\n"
"    .drop strong{display:block;color:#eef6ff;margin-top:7px}\n"
"    input[type=file]{display:none}\n"
"    textarea,.text-input{width:100%;border:1px solid #2c4565;border-radius:11px;background:#08111e;color:#fff;padding:12px;resize:vertical;min-height:72px}\n"
"    .or{display:flex;align-items:center;gap:12px;color:#637892;font-size:10px;text-transform:uppercase;letter-spacing:1px;margin:17px 0}\n"
"    .or:before,.or:after{content:\"\";height:1px;flex:1;background:var(--line)}\n"
"    .hint{margin:7px 0 0;font-size:10px;color:#6e829b}\n"
"    .paths{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;max-height:210px;overflow:auto;padding:2px}\n"
"    .path{border:1px solid #263d59;border-radius:11px;background:#0d1a2b;text-align:left;padding:11px;cursor:pointer;min-width:0}\n"
"    .path.selected{border-color:var(--blue);background:rgba(42,125,231,.14)}\n"
"    .path.unavailable{opacity:.45}\n"
"    .path-title{display:flex;align-items:center;gap:7px;font-size:12px;font-weight:800}\n"
"    .path-code{font:10px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;color:#758aa3;margin-top:4px;overflow:hidden;text-overflow:ellipsis}\n"
"    .form-footer{display:flex;justify-content:flex-end;gap:9px;margin-top:21px;padding-top:18px;border-top:1px solid var(--line)}\n"
"    .toast-wrap{position:fixed;z-index:200;right:24px;bottom:24px;display:grid;gap:8px}\n"
"    .toast{max-width:390px;padding:12px 15px;border:1px solid #345575;border-radius:11px;background:#122239;box-shadow:var(--shadow);font-size:12px;animation:toastin .2s ease}\n"
"    .toast.error{border-color:#92454c;color:#ffd1d4}\n"
"    .toast.success{border-color:#28754d;color:#d9ffea}\n"
"    @keyframes toastin{from{opacity:0;transform:translateY(8px)}}\n"
"    @media(max-width:900px){.summary{grid-template-columns:repeat(2,1fr)}.hero-row{align-items:flex-start;flex-direction:column}.details{grid-template-columns:repeat(3,1fr)}.torrent{grid-template-columns:1fr}.torrent-actions{justify-content:flex-end}}\n"
"    @media(max-width:620px){.shell{padding:16px 12px 42px}.brand p{display:none}.connection-label{display:none}.topbar{gap:10px}.toolbar .btn span{display:none}.hero{padding:22px 18px;border-radius:18px}.hero h2{font-size:28px}.summary{gap:8px}.metric{padding:14px}.metric-value{font-size:20px}.panel-head{align-items:flex-start;flex-direction:column}.filters{margin-left:0;width:100%;overflow:auto}.filter{flex:1}.torrent{padding:14px}.details{grid-template-columns:repeat(2,1fr)}.detail:nth-child(odd){border-left:0;padding-left:0}.paths{grid-template-columns:1fr}.state{margin-left:0}.torrent-top{flex-wrap:wrap}}\n"
"    @media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;animation:none!important;transition:none!important}}\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <main class=\"shell\">\n"
"    <header class=\"topbar\">\n"
"      <div class=\"brand\">\n"
"        <div class=\"logo\" aria-hidden=\"true\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"white\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 3v12m0 0 5-5m-5 5-5-5\"/><path d=\"M5 20h14\"/><circle cx=\"5\" cy=\"5\" r=\"1\" fill=\"white\" stroke=\"none\"/><circle cx=\"19\" cy=\"5\" r=\"1\" fill=\"white\" stroke=\"none\"/></svg></div>\n"
"        <div><h1>PS5Torrent</h1><p>Central de downloads do console</p></div>\n"
"      </div>\n"
"      <div class=\"connection\" id=\"connection\"><span class=\"connection-dot\"></span><span class=\"connection-label\">Conectando...</span></div>\n"
"      <div class=\"toolbar\"><button class=\"btn primary\" id=\"openAdd\"><svg class=\"icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M12 5v14M5 12h14\"/></svg><span>Novo torrent</span></button></div>\n"
"    </header>\n"
"\n"
"    <section class=\"hero\">\n"
"      <div class=\"hero-row\">\n"
"        <div>\n"
"          <div class=\"eyebrow\">Download em segundo plano</div>\n"
"          <h2>Acompanhe tudo sem sair do sofá.</h2>\n"
"          <p class=\"hero-copy\">Veja velocidade, progresso, tempo restante e peers direto no navegador do PS5. O serviço continua trabalhando enquanto o payload estiver ativo.</p>\n"
"          <div class=\"hero-meta\"><span class=\"chip\" id=\"versionChip\">PS5Torrent</span><span class=\"chip\" id=\"accessChip\">Verificando acesso...</span><span class=\"chip\" id=\"capacityChip\">Até 8 torrents</span></div>\n"
"        </div>\n"
"        <button class=\"btn\" id=\"refreshNow\"><svg class=\"icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M20 6v5h-5M4 18v-5h5\"/><path d=\"M18 9a7 7 0 0 0-12-2L4 11m2 4a7 7 0 0 0 12 2l2-4\"/></svg>Atualizar</button>\n"
"      </div>\n"
"    </section>\n"
"\n"
"    <section class=\"summary\" aria-label=\"Resumo\">\n"
"      <article class=\"metric\"><div class=\"metric-label\">Velocidade total</div><div class=\"metric-value\" id=\"totalSpeed\">0 B/s</div><div class=\"metric-sub\">download agora</div></article>\n"
"      <article class=\"metric\"><div class=\"metric-label\">Em andamento</div><div class=\"metric-value\" id=\"activeCount\">0</div><div class=\"metric-sub\" id=\"activeSub\">nenhum download</div></article>\n"
"      <article class=\"metric\"><div class=\"metric-label\">Transferido</div><div class=\"metric-value\" id=\"downloadedTotal\">0 B</div><div class=\"metric-sub\">nesta sessão</div></article>\n"
"      <article class=\"metric\"><div class=\"metric-label\">Peers ativos</div><div class=\"metric-value\" id=\"peerCount\">0</div><div class=\"metric-sub\">conexões recebendo dados</div></article>\n"
"    </section>\n"
"\n"
"    <section class=\"panel\">\n"
"      <div class=\"panel-head\">\n"
"        <div><div class=\"panel-title\">Downloads</div><div class=\"panel-note\" id=\"lastUpdate\">Aguardando o console...</div></div>\n"
"        <div class=\"filters\" role=\"tablist\">\n"
"          <button class=\"filter active\" data-filter=\"all\">Todos</button>\n"
"          <button class=\"filter\" data-filter=\"downloading\">Baixando</button>\n"
"          <button class=\"filter\" data-filter=\"done\">Concluídos</button>\n"
"          <button class=\"filter\" data-filter=\"error\">Atenção</button>\n"
"        </div>\n"
"      </div>\n"
"      <div class=\"torrent-list\" id=\"torrentList\"></div>\n"
"    </section>\n"
"  </main>\n"
"\n"
"  <div class=\"modal-backdrop hidden\" id=\"addModal\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"addTitle\">\n"
"    <section class=\"modal\">\n"
"      <div class=\"modal-head\"><h3 id=\"addTitle\">Adicionar download</h3><button class=\"close\" id=\"closeAdd\" aria-label=\"Fechar\">×</button></div>\n"
"      <div class=\"form\">\n"
"        <label class=\"label\">Arquivo .torrent</label>\n"
"        <label class=\"drop\" id=\"dropZone\" for=\"fileInput\"><svg class=\"icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M12 3v12m0 0 5-5m-5 5-5-5\"/><path d=\"M5 20h14\"/></svg><strong id=\"fileLabel\">Escolher arquivo .torrent</strong><span id=\"fileHelp\">Selecione no armazenamento acessível pelo navegador</span></label>\n"
"        <input type=\"file\" id=\"fileInput\" accept=\".torrent,application/x-bittorrent\">\n"
"        <div class=\"or\">ou link experimental</div>\n"
"        <label class=\"label\" for=\"magnetInput\">Link magnet</label>\n"
"        <textarea id=\"magnetInput\" placeholder=\"magnet:?xt=urn:btih:...\"></textarea>\n"
"        <p class=\"hint\">Links magnet ainda dependem de suporte a metadados BEP-9. Para downloads confiáveis, use o arquivo .torrent.</p>\n"
"        <div style=\"height:18px\"></div>\n"
"        <label class=\"label\">Salvar em</label>\n"
"        <div class=\"paths\" id=\"storagePaths\"></div>\n"
"        <div style=\"height:10px\"></div>\n"
"        <label class=\"label\" for=\"customPath\">Outro caminho</label>\n"
"        <input class=\"text-input\" id=\"customPath\" type=\"text\" placeholder=\"/mnt/usb0/\" style=\"min-height:44px\">\n"
"        <p class=\"hint\">Os arquivos serão organizados automaticamente na subpasta <strong>torrents</strong> do destino escolhido.</p>\n"
"        <div class=\"form-footer\"><button class=\"btn\" id=\"cancelAdd\">Cancelar</button><button class=\"btn primary\" id=\"startDownload\">Iniciar download</button></div>\n"
"      </div>\n"
"    </section>\n"
"  </div>\n"
"  <div class=\"toast-wrap\" id=\"toasts\" aria-live=\"polite\"></div>\n"
"\n"
"  <script>\n"
"    var state={torrents:[],filter:'all',selectedPath:'',selectedFile:null,busy:false};\n"
"    var labels={downloading:'Baixando',done:'Concluído',seeding:'Enviando',stopped:'Pausado',error:'Atenção'};\n"
"    var el=function(id){return document.getElementById(id)};\n"
"    function esc(value){return String(value==null?'':value).replace(/[&<>\"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'}[c]})}\n"
"    function fmtBytes(bytes){var n=Number(bytes)||0,u=['B','KB','MB','GB','TB'],i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return n.toFixed(i&&n<100?1:0)+' '+u[i]}\n"
"    function fmtSpeed(bytes){return fmtBytes(bytes)+'/s'}\n"
"    function fmtTime(seconds){if(!isFinite(seconds)||seconds<=0)return'Calculando';if(seconds<60)return Math.ceil(seconds)+' s';if(seconds<3600)return Math.ceil(seconds/60)+' min';if(seconds<86400)return Math.floor(seconds/3600)+' h '+Math.ceil((seconds%3600)/60)+' min';return Math.floor(seconds/86400)+' d '+Math.ceil((seconds%86400)/3600)+' h'}\n"
"    function iconDownload(){return'<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M12 3v12m0 0 5-5m-5 5-5-5\"/><path d=\"M5 20h14\"/></svg>'}\n"
"    function setConnection(mode,text){var c=el('connection');c.className='connection '+mode;c.querySelector('.connection-label').textContent=text}\n"
"    function toast(message,type){var node=document.createElement('div');node.className='toast '+(type||'');node.textContent=message;el('toasts').appendChild(node);setTimeout(function(){node.remove()},4200)}\n"
"    function openModal(){el('addModal').classList.remove('hidden');setTimeout(function(){el('fileInput').focus()},50)}\n"
"    function closeModal(){el('addModal').classList.add('hidden')}\n"
"    function setFilter(filter){state.filter=filter;document.querySelectorAll('.filter').forEach(function(btn){btn.classList.toggle('active',btn.getAttribute('data-filter')===filter)});render()}\n"
"    function visibleTorrent(t){if(state.filter==='all')return true;if(state.filter==='error')return t.state==='error'||t.state==='stopped';return t.state===state.filter}\n"
"    function torrentCard(t){\n"
"      var pct=Math.max(0,Math.min(100,Math.round((Number(t.progress)||0)*100)));\n"
"      var remaining=Math.max(0,(Number(t.size)||0)-(Number(t.downloaded)||0));\n"
"      var eta=t.state==='done'?'Finalizado':(t.state==='downloading'?fmtTime(remaining/(Number(t.speed_down)||0)):'—');\n"
"      var canStop=t.state==='downloading'||t.state==='seeding';\n"
"      var canStart=t.state==='stopped'||t.state==='error';\n"
"      return '<article class=\"torrent '+(t.state==='done'?'done':'')+'\">'+\n"
"        '<div><div class=\"torrent-top\"><div class=\"torrent-symbol\">'+iconDownload()+'</div><div style=\"min-width:0\"><div class=\"torrent-name\">'+esc(t.name||'Torrent sem nome')+'</div><div class=\"torrent-hash\">'+esc(t.hash||'')+'</div></div><span class=\"state state-'+esc(t.state)+'\">'+esc(labels[t.state]||t.state)+'</span></div>'+\n"
"        '<div class=\"progress-line\"><div class=\"track\"><div class=\"fill\" style=\"width:'+pct+'%\"></div></div><div class=\"pct\">'+pct+'%</div></div>'+\n"
"        '<div class=\"details\"><div class=\"detail\"><span>Velocidade</span><strong>'+fmtSpeed(t.speed_down)+'</strong></div><div class=\"detail\"><span>Restante</span><strong>'+fmtBytes(remaining)+'</strong></div><div class=\"detail\"><span>Tempo</span><strong>'+eta+'</strong></div><div class=\"detail\"><span>Baixado</span><strong>'+fmtBytes(t.downloaded)+'</strong></div><div class=\"detail\"><span>Peers</span><strong>'+Number(t.active_peers||0)+' / '+Number(t.peers||0)+'</strong></div></div>'+\n"
"        '<div class=\"save-path\">Destino: '+esc(t.save_path||'—')+'</div></div>'+\n"
"        '<div class=\"torrent-actions\">'+(canStop?'<button class=\"btn small\" data-action=\"stop\" data-id=\"'+t.id+'\">Pausar</button>':'')+(canStart?'<button class=\"btn small primary\" data-action=\"start\" data-id=\"'+t.id+'\">Reiniciar</button>':'')+'<button class=\"btn small danger\" data-action=\"remove\" data-id=\"'+t.id+'\">Remover</button></div>'+\n"
"        (t.error?'<div class=\"error-msg\">'+esc(t.error)+'</div>':'')+'</article>'\n"
"    }\n"
"    function render(){\n"
"      var torrents=state.torrents||[],active=0,speed=0,downloaded=0,peers=0;\n"
"      torrents.forEach(function(t){if(t.state==='downloading'||t.state==='seeding')active++;speed+=Number(t.speed_down)||0;downloaded+=Number(t.downloaded)||0;peers+=Number(t.active_peers)||0});\n"
"      el('totalSpeed').textContent=fmtSpeed(speed);el('activeCount').textContent=active;el('activeSub').textContent=active===1?'1 download ativo':active+' downloads ativos';el('downloadedTotal').textContent=fmtBytes(downloaded);el('peerCount').textContent=peers;\n"
"      var shown=torrents.filter(visibleTorrent),list=el('torrentList');\n"
"      if(!shown.length){list.innerHTML='<div class=\"empty\"><div><div class=\"empty-mark\">'+iconDownload()+'</div><strong>'+(torrents.length?'Nada neste filtro':'Nenhum download adicionado')+'</strong><span>'+(torrents.length?'Selecione outra categoria acima.':'Use “Novo torrent” para começar.')+'</span></div></div>';return}\n"
"      list.innerHTML=shown.map(torrentCard).join('');\n"
"    }\n"
"    function fetchJson(url,options){return fetch(url,options).then(function(response){return response.json().then(function(data){if(!response.ok)throw new Error(data.error||'Falha na solicitação');return data})})}\n"
"    function refresh(){\n"
"      return Promise.all([fetchJson('/api/torrents'),fetchJson('/api/status')]).then(function(results){state.torrents=results[0].torrents||[];var info=results[1];setConnection('online','Console conectado');el('versionChip').textContent='PS5Torrent v'+(info.version||'2.0');el('accessChip').textContent=info.jailbroken?'Acesso etaHEN liberado':'Acesso do ELF atual';el('capacityChip').textContent='Até '+(info.capacity||8)+' torrents';el('lastUpdate').textContent='Atualizado às '+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit'});render()}).catch(function(){setConnection('offline','Sem conexão');el('lastUpdate').textContent='Não foi possível falar com o serviço';render()})\n"
"    }\n"
"    function loadPaths(){\n"
"      return fetchJson('/api/paths').then(function(data){var paths=data.paths||[],available=paths.filter(function(p){return p.exists&&p.writable}),saved='';try{saved=localStorage.getItem('ps5torrent.path')||''}catch(e){}if(!state.selectedPath&&available.some(function(p){return p.path===saved}))state.selectedPath=saved;if(!available.some(function(p){return p.path===state.selectedPath}))state.selectedPath=available.length?available[0].path:'';var box=el('storagePaths');box.innerHTML=paths.map(function(p){var usable=p.exists&&p.writable,status=!p.exists?'não montado':(p.writable?'gravável':'sem permissão');return'<button type=\"button\" class=\"path '+(p.path===state.selectedPath?'selected ':'')+(usable?'':'unavailable')+'\" data-path=\"'+esc(p.path)+'\" '+(usable?'':'disabled')+'><div class=\"path-title\"><span>'+(p.removable?'USB':'Disco')+'</span><span>'+esc(p.label)+'</span></div><div class=\"path-code\">'+esc(p.path)+' · '+status+'</div></button>'}).join('')+(!available.length?'<div class=\"hint\">Nenhum destino gravável. No etaHEN, ative Network e Legacy CMD server e reabra o app.</div>':'')}).catch(function(){el('storagePaths').innerHTML='<div class=\"hint\">Não foi possível consultar os discos agora.</div>'})\n"
"    }\n"
"    function selectPath(path){state.selectedPath=path;try{localStorage.setItem('ps5torrent.path',path)}catch(e){}el('customPath').value='';document.querySelectorAll('.path').forEach(function(node){node.classList.toggle('selected',node.getAttribute('data-path')===path)})}\n"
"    function torrentAction(id,action){if(action==='remove'&&!confirm('Remover este torrent da lista? Os arquivos já gravados não serão apagados.'))return;fetchJson('/api/torrents/'+id+'/'+action,{method:'POST'}).then(function(){toast(action==='remove'?'Torrent removido.':'Status atualizado.','success');refresh()}).catch(function(e){toast(e.message,'error')})}\n"
"    function resetForm(){state.selectedFile=null;el('fileInput').value='';el('fileLabel').textContent='Escolher arquivo .torrent';el('fileHelp').textContent='Selecione no armazenamento acessível pelo navegador';el('dropZone').classList.remove('has-file');el('magnetInput').value=''}\n"
"    function addTorrent(){\n"
"      if(state.busy)return;var magnet=el('magnetInput').value.trim(),path=el('customPath').value.trim()||state.selectedPath;\n"
"      if(!state.selectedFile&&!magnet){toast('Escolha um arquivo .torrent ou informe um link magnet.','error');return}\n"
"      if(!path){toast('Nenhum destino gravável foi encontrado.','error');return}\n"
"      state.busy=true;el('startDownload').disabled=true;el('startDownload').textContent='Adicionando...';\n"
"      try{localStorage.setItem('ps5torrent.path',path)}catch(e){}var request;if(state.selectedFile){var form=new FormData();form.append('path',path);form.append('torrent',state.selectedFile);request=fetchJson('/api/torrents/upload',{method:'POST',body:form})}else{request=fetchJson('/api/torrents/add',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'magnet='+encodeURIComponent(magnet)+'&path='+encodeURIComponent(path)})}\n"
"      function finish(){state.busy=false;el('startDownload').disabled=false;el('startDownload').textContent='Iniciar download'}\n"
"      request.then(function(data){toast('Download adicionado: '+(data.name||'torrent'),'success');resetForm();closeModal();refresh();finish()},function(e){toast(e.message,'error');finish()})\n"
"    }\n"
"    el('openAdd').onclick=function(){openModal();loadPaths()};el('closeAdd').onclick=closeModal;el('cancelAdd').onclick=closeModal;el('startDownload').onclick=addTorrent;el('refreshNow').onclick=refresh;\n"
"    el('fileInput').onchange=function(event){var file=event.target.files[0];state.selectedFile=file||null;if(file){el('fileLabel').textContent=file.name;el('fileHelp').textContent=fmtBytes(file.size)+' · pronto para enviar';el('dropZone').classList.add('has-file')}};\n"
"    el('customPath').oninput=function(){if(this.value.trim())document.querySelectorAll('.path').forEach(function(node){node.classList.remove('selected')})};\n"
"    el('storagePaths').onclick=function(event){var node=event.target.closest('.path');if(node)selectPath(node.getAttribute('data-path'))};\n"
"    el('torrentList').onclick=function(event){var btn=event.target.closest('[data-action]');if(btn)torrentAction(Number(btn.getAttribute('data-id')),btn.getAttribute('data-action'))};\n"
"    document.querySelectorAll('.filter').forEach(function(btn){btn.onclick=function(){setFilter(btn.getAttribute('data-filter'))}});\n"
"    el('addModal').onclick=function(event){if(event.target===el('addModal'))closeModal()};\n"
"    document.addEventListener('keydown',function(event){if(event.key==='Escape')closeModal();if(event.key==='n'&&!/INPUT|TEXTAREA/.test(document.activeElement.tagName))openModal()});\n"
"    loadPaths();refresh();setInterval(refresh,2000);\n"
"  </script>\n"
"</body>\n"
"</html>\n"
;

#endif /* PS5TORRENT_WEB_CONTENT_H */
