#ifndef PS5TORRENT_WEB_CONTENT_H
#define PS5TORRENT_WEB_CONTENT_H

/**
 * Web interface HTML content - full single-page app with CSS and JS embedded.
 * This is served by the HTTP server when accessing http://PS5_IP:8080/
 */

static const char web_index_html[] =
"<!DOCTYPE html>"
"<html lang=\"pt-BR\">"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
"<title>PS5Torrent - Download Manager</title>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
":root{--bg:#0d1117;--bg2:#161b22;--bg3:#21262d;--border:#30363d;"
"--text:#c9d1d9;--text2:#8b949e;--accent:#58a6ff;--accent2:#1f6feb;"
"--green:#3fb950;--orange:#d29922;--red:#f85149;--purple:#bc8cff}"
"body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;"
"background:var(--bg);color:var(--text);line-height:1.5;min-height:100vh}"
".container{max-width:1100px;margin:0 auto;padding:16px}"
/* Header */
"header{background:var(--bg2);border-bottom:1px solid var(--border);"
"padding:12px 0;position:sticky;top:0;z-index:100}"
"header .container{display:flex;align-items:center;gap:12px}"
"header h1{font-size:22px;font-weight:700;background:linear-gradient(135deg,"
"var(--accent),var(--purple));-webkit-background-clip:text;"
"-webkit-text-fill-color:transparent;background-clip:text}"
"header .subtitle{color:var(--text2);font-size:13px}"
"header .status{font-size:12px;padding:4px 10px;border-radius:12px;"
"background:var(--bg3);border:1px solid var(--border);margin-left:auto}"
".dot{display:inline-block;width:8px;height:8px;border-radius:50%;"
"margin-right:5px;animation:pulse 2s infinite}"
".dot.green{background:var(--green);box-shadow:0 0 6px var(--green)}"
".dot.red{background:var(--red)}"
"@keyframes pulse{0%,100%{opacity:1}50%{opacity:.5}}"
/* Cards */
".card{background:var(--bg2);border:1px solid var(--border);"
"border-radius:8px;padding:16px;margin-bottom:16px}"
".card h2{font-size:16px;margin-bottom:12px;display:flex;align-items:center;gap:8px}"
".card h2 .icon{font-size:20px}"
/* Form */
".form-group{margin-bottom:12px}"
".form-group label{display:block;font-size:13px;color:var(--text2);margin-bottom:4px}"
"input[type=text],select,textarea{width:100%;padding:10px 12px;"
"background:var(--bg3);border:1px solid var(--border);border-radius:6px;"
"color:var(--text);font-size:14px;transition:border .2s}"
"input[type=text]:focus,select:focus,textarea:focus{outline:none;border-color:var(--accent)}"
"textarea{resize:vertical;min-height:60px;font-family:monospace}"
"input[type=file]{display:none}"
".file-btn{display:inline-flex;align-items:center;gap:8px;padding:10px 16px;"
"background:var(--bg3);border:1px dashed var(--border);border-radius:6px;"
"cursor:pointer;font-size:14px;color:var(--text2);transition:all .2s;width:100%}"
".file-btn:hover{border-color:var(--accent);color:var(--text)}"
/* Buttons */
".btn{display:inline-flex;align-items:center;gap:6px;padding:10px 20px;"
"border:none;border-radius:6px;font-size:14px;font-weight:500;cursor:pointer;"
"transition:all .2s}"
".btn-primary{background:var(--accent2);color:#fff}"
".btn-primary:hover{background:#388bfd;transform:translateY(-1px)}"
".btn-danger{background:var(--red);color:#fff}"
".btn-danger:hover{opacity:.9;transform:translateY(-1px)}"
".btn-secondary{background:var(--bg3);color:var(--text);border:1px solid var(--border)}"
".btn-secondary:hover{border-color:var(--text2)}"
".btn-sm{padding:6px 12px;font-size:12px}"
".btn-group{display:flex;gap:8px;margin-top:12px;flex-wrap:wrap}"
/* Torrent list */
".torrent-list{margin-top:8px}"
".torrent-item{background:var(--bg3);border:1px solid var(--border);"
"border-radius:8px;padding:14px;margin-bottom:8px;transition:border .2s}"
".torrent-item:hover{border-color:var(--accent)}"
".torrent-item .top{display:flex;justify-content:space-between;align-items:start;gap:8px}"
".torrent-item .name{font-size:15px;font-weight:600;word-break:break-word}"
".torrent-item .hash{font-size:11px;color:var(--text2);font-family:monospace;margin-top:2px}"
".torrent-item .state{font-size:11px;padding:2px 8px;border-radius:10px;"
"text-transform:uppercase;font-weight:600;white-space:nowrap}"
".state-downloading{background:#0a2e1a;color:var(--green)}"
".state-done{background:#0a2e1a;color:var(--green)}"
".state-stopped{background:var(--bg3);color:var(--text2);border:1px solid var(--border)}"
".state-error{background:#2e0a0a;color:var(--red)}"
".state-seeding{background:#1a1a0a;color:var(--orange)}"
/* Progress bar */
".progress-bar{width:100%;height:6px;background:var(--bg);border-radius:3px;"
"margin:8px 0;overflow:hidden}"
".progress-fill{height:100%;border-radius:3px;transition:width .5s ease;"
"background:linear-gradient(90deg,var(--accent2),var(--accent))}"
".progress-fill.done{background:linear-gradient(90deg,var(--green),#56d364)}"
/* Stats */
".stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:8px;margin:8px 0}"
".stat{font-size:12px;color:var(--text2)}"
".stat strong{display:block;font-size:14px;color:var(--text);font-weight:600}"
/* Actions */
".actions{display:flex;gap:6px;margin-top:8px;flex-wrap:wrap}"
/* Divider */
".divider{text-align:center;color:var(--text2);font-size:12px;margin:12px 0;"
"position:relative}"
".divider::before,.divider::after{content:'';position:absolute;top:50%;"
"width:42%;height:1px;background:var(--border)}"
".divider::before{left:0}"
".divider::after{right:0}"
/* Toast notifications */
".toast-container{position:fixed;bottom:20px;right:20px;z-index:999;display:flex;"
"flex-direction:column;gap:8px}"
".toast{background:var(--bg3);border:1px solid var(--border);border-radius:8px;"
"padding:12px 16px;font-size:13px;animation:slideIn .3s ease;max-width:360px}"
".toast.success{border-color:var(--green)}"
".toast.error{border-color:var(--red)}"
"@keyframes slideIn{from{transform:translateX(100%);opacity:0}"
"to{transform:translateX(0);opacity:1}}"
/* Torrent actions inside item */
".torrent-actions button{padding:4px 10px;font-size:11px}"
/* Empty state */
".empty-state{text-align:center;padding:32px;color:var(--text2)}"
".empty-state .big-icon{font-size:48px;margin-bottom:12px}"
/* Storage paths */
".path-option{padding:10px 12px;background:var(--bg3);border:1px solid var(--border);"
"border-radius:6px;margin-bottom:4px;cursor:pointer;transition:all .2s;"
"display:flex;align-items:center;gap:10px}"
".path-option:hover{border-color:var(--accent)}"
".path-option.selected{border-color:var(--accent);background:#0a1a2e}"
".path-option .path-icon{font-size:18px}"
".path-option .path-label{font-size:13px}"
".path-option .path-str{font-size:11px;color:var(--text2);font-family:monospace}"
/* Responsive */
"@media(max-width:600px){header h1{font-size:18px}"
".stats{grid-template-columns:repeat(2,1fr)}"
".container{padding:10px}"
".torrent-item .top{flex-direction:column}}"
"</style>"
"</head>"
"<body>"
"<header>"
"<div class=container>"
"<h1>🎮 PS5Torrent</h1>"
"<span class=subtitle>Download Manager</span>"
"<span class=status id=headerStatus><span class=\"dot green\"></span>Connected</span>"
"</div>"
"</header>"
"<div class=container>"
"<!-- Add Torrent Card -->"
"<div class=card id=addCard>"
"<h2><span class=icon>📥</span>Add New Torrent</h2>"
"<div class=form-group>"
"<label>Magnet Link or .torrent URL</label>"
"<textarea id=magnetInput placeholder=\"magnet:?xt=urn:btih:...\"></textarea>"
"</div>"
"<div class=divider>OR</div>"
"<div class=form-group>"
"<label>Upload .torrent File</label>"
"<label class=file-btn for=fileInput>📁 Choose .torrent file...</label>"
"<input type=file id=fileInput accept=.torrent>"
"<span id=fileName style=\"font-size:12px;color:var(--text2);margin-top:4px;display:block\"></span>"
"</div>"
"<div class=form-group>"
"<label>💾 Save to</label>"
"<div id=storagePaths></div>"
"<div style=margin-top:6px>"
"<input type=text id=customPath placeholder=\"/custom/path/\" style=\"font-size:13px\">"
"</div>"
"</div>"
"<button class=\"btn btn-primary\" onclick=addTorrent()>"
"⬇️ Start Download</button>"
"</div>"
"<!-- Active Downloads -->"
"<div class=card>"
"<h2><span class=icon>📊</span>Downloads</h2>"
"<div class=torrent-list id=torrentList>"
"<div class=empty-state id=emptyState>"
"<div class=big-icon>📥</div>"
"<div>No active torrents</div>"
"<div style=font-size:12px;margin-top:4px>"
"Add a magnet link or upload a .torrent file above</div>"
"</div>"
"</div>"
"</div>"
"<!-- Global Stats -->"
"<div class=card id=globalStatsCard style=display:none>"
"<h2><span class=icon>📈</span>Global Statistics</h2>"
"<div class=stats style=margin:0>"
"<div class=stat><strong id=globalDl>0 B/s</strong>Download</div>"
"<div class=stat><strong id=globalUl>0 B/s</strong>Upload</div>"
"<div class=stat><strong id=globalPeers>0</strong>Active Peers</div>"
"<div class=stat><strong id=globalActive>0</strong>Active Torrents</div>"
"</div>"
"</div>"
"</div>"
"<!-- Toast container -->"
"<div class=toast-container id=toastContainer></div>"
"<script>"
// Storage paths
"const STORAGE_PATHS=["
"{path:'/mnt/usb0/',label:'USB Pendrive (usb0)',icon:'💾'},"
"{path:'/mnt/usb1/',label:'Second USB (usb1)',icon:'💾'},"
"{path:'/mnt/usb2/',label:'Third USB (usb2)',icon:'💾'},"
"{path:'/mnt/nvme0/',label:'NVMe SSD (nvme0)',icon:'💿'},"
"{path:'/mnt/nvme1/',label:'Second NVMe (nvme1)',icon:'💿'},"
"{path:'/mnt/ext0/',label:'External HDD (ext0)',icon:'💽'},"
"{path:'/mnt/ext1/',label:'Second External (ext1)',icon:'💽'},"
"{path:'/data/',label:'System Data (internal)',icon:'🔧'},"
"{path:'/system_data/',label:'System Data (alt)',icon:'🔧'},"
"{path:'/mnt/sata0/',label:'SATA SSD (sata0)',icon:'🖴'},"
"{path:'/user/',label:'User Data',icon:'👤'},"
"{path:'/tmp/',label:'Temp (RAM)',icon:'⚡'}"
"];"
"let selectedPath='/mnt/usb0/';"
"let selectedFile=null;"
// Init storage paths
"function initPaths(){"
"const container=document.getElementById('storagePaths');"
"container.innerHTML='';"
"STORAGE_PATHS.forEach(sp=>{"
"const div=document.createElement('div');"
"div.className='path-option'+(sp.path===selectedPath?' selected':'');"
"div.innerHTML="
"`<span class=path-icon>${sp.icon}</span>"
"<div><div class=path-label>${sp.label}</div>"
"<div class=path-str>${sp.path}</div></div>`;"
"div.onclick=()=>{"
"document.querySelectorAll('.path-option').forEach(p=>p.classList.remove('selected'));"
"div.classList.add('selected');selectedPath=sp.path;"
"document.getElementById('customPath').value='';"
"};"
"container.appendChild(div);"
"})"
"}"
// File input handler
"document.getElementById('fileInput').onchange=function(e){"
"const f=e.target.files[0];"
"if(f){selectedFile=f;"
"document.getElementById('fileName').textContent='📄 '+f.name;"
"}else{selectedFile=null;"
"document.getElementById('fileName').textContent=''}"
"};"
// Custom path handler
"document.getElementById('customPath').oninput=function(){"
"if(this.value.trim()){"
"selectedPath=this.value.trim();"
"document.querySelectorAll('.path-option').forEach(p=>p.classList.remove('selected'));"
"}"
"};"
// Format bytes
"function fmtBytes(b){"
"if(!b||b===0)return'0 B';"
"const u=['B','KB','MB','GB','TB'];"
"let i=0;"
"let v=b;"
"while(v>=1024&&i<u.length-1){v/=1024;i++}"
"return v.toFixed(i>0?1:0)+' '+u[i]"
"}"
// Format speed
"function fmtSpeed(b){return fmtBytes(b)+'/s'}"
// Show toast
"function showToast(msg,type){"
"const c=document.getElementById('toastContainer');"
"const t=document.createElement('div');"
"t.className='toast '+type;"
"t.textContent=msg;"
"c.appendChild(t);"
"setTimeout(()=>{t.style.opacity='0';t.style.transition='opacity .3s';"
"setTimeout(()=>t.remove(),300)},4000)"
"}"
// Add torrent
"async function addTorrent(){"
"const magnet=document.getElementById('magnetInput').value.trim();"
"if(!magnet&&!selectedFile){"
"showToast('Please paste a magnet link or select a .torrent file','error');return"
"}"
"if(magnet){"
"try{"
"const r=await fetch('/api/torrents/add',{"
"method:'POST',"
"headers:{'Content-Type':'application/x-www-form-urlencoded'},"
"body:'magnet='+encodeURIComponent(magnet)+'&path='+encodeURIComponent(selectedPath)"
"});"
"const d=await r.json();"
"if(d.success){showToast('Torrent added: '+d.name,'success');"
"document.getElementById('magnetInput').value=''"
"}else showToast('Error: '+d.error,'error')"
"}catch(e){showToast('Connection error','error')}"
"}else if(selectedFile){"
"const fd=new FormData();"
"fd.append('torrent',selectedFile);"
"fd.append('path',selectedPath);"
"try{"
"const r=await fetch('/api/torrents/upload',{method:'POST',body:fd});"
"const d=await r.json();"
"if(d.success){showToast('Torrent added: '+d.name,'success');"
"document.getElementById('fileName').textContent='';selectedFile=null;"
"document.getElementById('fileInput').value=''"
"}else showToast('Error: '+d.error,'error')"
"}catch(e){showToast('Connection error','error')}"
"}"
"}"
// Torrent actions
"async function torrentAction(id,action){"
"try{"
"const r=await fetch('/api/torrents/'+id+'/'+action,{method:'POST'});"
"const d=await r.json();"
"if(d.success){"
"showToast('Torrent '+action+'ed','success');refreshTorrents()"
"}else showToast('Error: '+d.error,'error')"
"}catch(e){showToast('Connection error','error')}"
"}"
// Render torrent item
"function renderTorrent(t){"
"const div=document.createElement('div');"
"div.className='torrent-item';"
"div.id='torrent-'+t.id;"
"const pct=Math.round(t.progress*100);"
"const done=t.state==='done';"
"const isDl=t.state==='downloading';"
"div.innerHTML="
"`<div class=top>"
"<div><div class=name>${t.name}</div>"
"<div class=hash>${t.hash}</div></div>"
"<span class=\"state state-${t.state}\">${t.state}</span>"
"</div>"
"<div class=progress-bar><div class=\"progress-fill${done?' done':''}\" "
"style=\"width:${pct}%\"></div></div>"
"<div class=stats>"
"<div class=stat><strong>${fmtBytes(t.downloaded)}</strong>Downloaded</div>"
"<div class=stat><strong>${fmtBytes(t.uploaded)}</strong>Uploaded</div>"
"<div class=stat><strong>${isDl?fmtSpeed(t.speed_down):'0 B/s'}</strong>Speed DL</div>"
"<div class=stat><strong>${isDl?fmtSpeed(t.speed_up):'0 B/s'}</strong>Speed UL</div>"
"<div class=stat><strong>${t.active_peers}/${t.peers}</strong>Peers</div>"
"<div class=stat><strong>${fmtBytes(t.size)}</strong>Total</div>"
"</div>"
"<div style=\"font-size:11px;color:var(--text2)\">${t.save_path}</div>"
"<div class=actions>"
"${!done&&t.state!=='error'?`"
"<button class=\"btn btn-sm btn-secondary\" onclick=\"torrentAction(${t.id},'stop')\">⏸ Stop</button>`:''}"
"${t.state==='stopped'||t.state==='error'?`"
"<button class=\"btn btn-sm btn-primary\" onclick=\"torrentAction(${t.id},'start')\">▶ Resume</button>`:''}"
"<button class=\"btn btn-sm btn-danger\" onclick=\"torrentAction(${t.id},'remove')\">🗑 Remove</button>"
"${t.error?`<span style=font-size:11px;color:var(--red);margin-left:8px>${t.error}</span>`:''}"
"</div>`;"
"return div"
"}"
// Refresh torrents
"async function refreshTorrents(){"
"try{"
"const r=await fetch('/api/torrents');"
"const d=await r.json();"
"const list=document.getElementById('torrentList');"
"const empty=document.getElementById('emptyState');"
"const stats=document.getElementById('globalStatsCard');"
"list.innerHTML='';"
"if(!d.torrents||d.torrents.length===0){"
"list.appendChild(empty);stats.style.display='none';return"
"}"
"stats.style.display='block';"
"let totalDl=0,totalUl=0,totalPeers=0;"
"d.torrents.forEach(t=>{"
"list.appendChild(renderTorrent(t));"
"totalDl+=t.speed_down;totalUl+=t.speed_up;totalPeers+=t.active_peers"
"});"
"document.getElementById('globalDl').textContent=fmtSpeed(totalDl);"
"document.getElementById('globalUl').textContent=fmtSpeed(totalUl);"
"document.getElementById('globalPeers').textContent=totalPeers;"
"document.getElementById('globalActive').textContent=d.torrents.length;"
"}catch(e){console.log('Refresh error:',e)}"
"}"
// Auto-refresh every 2 seconds
"initPaths();"
"setInterval(refreshTorrents,2000);"
"setTimeout(refreshTorrents,500);"
"</script>"
"</body>"
"</html>";

#endif /* PS5TORRENT_WEB_CONTENT_H */
